# Represents the shift register pin at which each stop's LED
# is plugged into

blue = {
"Bowdoin" : 8,
"Government Center" : 9,
"State" : 10,
"Aquarium" : 11,
"Maverick" : 0,
"Airport" : 1,
"Wood Island" : 2,
"Orient Heights" : 3,
"Suffolk Downs" : 4,
"Beachmont" : 5,
"Revere Beach" : 6,
"Wonderland" : 7
}

orange = {
"Forest Hills" : 16,
"Green Street" : 17,
"Stony Brook" : 18,
"Jackson Square" : 19,
"Roxbury Crossing" : 8,
"Ruggles" : 9,
"Massachusetts Avenue" : 10,
"Back Bay" : 11,
"Tufts Medical Center" : 12,
"Chinatown" : 13,
"Downtown Crossing" : 14,
"State" : 15,
"Haymarket" : 0,
"North Station" : 1,
"Community College" : 2,
"Sullivan Square" : 3,
"Assembly" : 4,
"Wellington" : 5,
"Malden Center" : 6,
"Oak Grove" : 7
}

red = {
"Alewife" : 10,
"Davis" : 9,
"Porter" : 8,
"Harvard" : 21,
"Central" : 20,
"Kendall/MIT" : 19,
"Charles/MGH" : 18,
"Park Street" : 17,
"Downtown Crossing" : 16,
"South Station" : 7,
"Broadway" : 6,
"Andrew" : 5,
"JFK/UMass" : 4,
"Savin Hill" : 14,
"Fields Corner" : 13,
"Shawmut" : 12,
"Ashmont" : 11,
"North Quincy" : 3,
"Wollaston" : 2,
"Quincy Center" : 1,
"Quincy Adams" : 0,
"Braintree" : 15
}

# 56 not lit up
# 47-43 unlit


green = {
    "Boston College": 23,
    "South Street": 22,
    "Chestnut Hill Avenue": 20,
    "Chiswick Road": 19,
    "Sutherland Road": 18,
    "Washington Street": 17,
    "Warren Street": 16,
    "Allston Street": 31,
    "Griggs Street": 30,
    "Harvard Avenue": 29,
    "Packards Corner": 28,
    "Babcock Street": 27,
    "Pleasant Street": 0,
    "Saint Paul Street": 54,
    "Boston University West": 55,
    "Boston University Central": 41,
    "Boston University East": 42,
    "Blandford Street": 0,
    "Cleveland Circle": 60,
    "Englewood Avenue": 52,
    "Dean Road": 61,
    "Tappan Street": 62,
    "Washington Square": 0,
    "Fairbanks Street": 63,
    "Brandon Hall": 48,
    "Summit Avenue": 49,
    "Coolidge Corner": 50,
    "Saint Paul Street": 51,
    "Kent Street": 53,
    "Hawes Street": 40,
    "Saint Marys Street": 0,
    "Riverside": 0,
    "Woodland": 0,
    "Waban": 0,
    "Eliot": 0,
    "Newton Highlands": 0,
    "Newton Centre": 0,
    "Chestnut Hill": 0,
    "Reservoir": 0,
    "Beaconsfield": 0,
    "Brookline Hills": 0,
    "Brookline Village": 0,
    "Longwood": 0,
    "Fenway": 0,
    "Kenmore": 58,
    "Hynes Convention Center": 57,
    "Heath Street": 64,
    "Back of the Hill": 65,
    "Riverway": 68,
    "Mission Park": 66,
    "Fenwood Road": 70,
    "Brigham Circle": 71,
    "Longwood Medical Area": 69,
    "Museum of Fine Arts": 67,
    "Northeastern University": 57,
    "Symphony": 58,
    "Prudential": 59,
    "Copley": 56,
    "Arlington": 71,
    "Boylston": 70,
    "Park Street": 69,
    "Government Center": 68,
    "Haymarket": 67,
    "North Station": 66,
    "Science Park/West End": 65,
    "Lechmere": 64
}
