# Represents the shift register pin at which each stop's LED is plugged into
blue = {
    "Bowdoin": 8,
    "Government Center": 9,
    "State": 10,
    "Aquarium": 11,
    "Maverick": 0,
    "Airport": 1,
    "Wood Island": 2,
    "Orient Heights": 3,
    "Suffolk Downs": 4,
    "Beachmont": 5,
    "Revere Beach": 6,
    "Wonderland": 7
}

orange = {
    "Forest Hills": 16,
    "Green Street": 17,
    "Stony Brook": 18,
    "Jackson Square": 19,
    "Roxbury Crossing": 8,
    "Ruggles": 9,
    "Massachusetts Avenue": 10,
    "Back Bay": 11,
    "Tufts Medical Center": 12,
    "Chinatown": 13,
    "Downtown Crossing": 14,
    "State": 15,
    "Haymarket": 0,
    "North Station": 1,
    "Community College": 2,
    "Sullivan Square": 3,
    "Assembly": 4,
    "Wellington": 5,
    "Malden Center": 6,
    "Oak Grove": 7
}

red = {
    "Alewife": 10,
    "Davis": 9,
    "Porter": 8,
    "Harvard": 21,
    "Central": 20,
    "Kendall/MIT": 19,
    "Charles/MGH": 18,
    "Park Street": 17,
    "Downtown Crossing": 16,
    "South Station": 7,
    "Broadway": 6,
    "Andrew": 5,
    "JFK/UMass": 4,
    "Savin Hill": 14,
    "Fields Corner": 13,
    "Shawmut": 12,
    "Ashmont": 11,
    "North Quincy": 3,
    "Wollaston": 2,
    "Quincy Center": 1,
    "Quincy Adams": 0,
    "Braintree": 15
}

# 21

green = {
    "Boston College": 23,
    "South Street": 22,
    "Chestnut Hill Avenue": 20,
    "Chiswick Road": 19,
    "Sutherland Road": 18,
    "Washington Street": 17,
    "Warren Street": 16,
    "Allston Street": 31,
    "Griggs Street": 30,
    "Harvard Avenue": 29,
    "Packards Corner": 28,
    "Babcock Street": 27,
    "Pleasant Street": 21,
    "Saint Paul Street": 47,
    "Boston University West": 46,
    "Boston University Central": 44,
    "Boston University East": 43,
    "Blandford Street": 42,
    "Cleveland Circle": 26,
    "Englewood Avenue": 25,
    "Dean Road": 24,
    "Tappan Street": 39,
    "Washington Square": 38,
    "Fairbanks Street": 37,
    "Brandon Hall": 36,
    "Summit Avenue": 35,
    "Coolidge Corner": 34,
    "Saint Paul Street": 33,
    "Kent Street": 32,
    "Hawes Street": 45,
    "Saint Marys Street": 54,
    "Riverside": 56,
    "Woodland": 61,
    "Waban": 63,
    "Eliot": 62,
    "Newton Highlands": 48,
    "Newton Centre": 49,
    "Chestnut Hill": 51,
    "Reservoir": 52,
    "Beaconsfield": 50,
    "Brookline Hills": 53,
    "Brookline Village": 55,
    "Longwood": 40,
    "Fenway": 41,
    "Kenmore": 60,
    "Hynes Convention Center": 8,
    "Heath Street": 64,
    "Back of the Hill": 65,
    "Riverway": 68,
    "Mission Park": 66,
    "Fenwood Road": 70,
    "Brigham Circle": 71,
    "Longwood Medical Area": 69,
    "Museum of Fine Arts": 67,
    "Northeastern University": 57,
    "Symphony": 58,
    "Prudential": 59,
    "Copley": 9,
    "Arlington": 11,
    "Boylston": 12,
    "Park Street": 13,
    "Government Center": 7,
    "Haymarket": 14,
    "North Station": 15,
    "Science Park/West End": 0,
    "Lechmere": 1
}
